name: PR enforcer

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  conventional:
    name: Conventional PR
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: "fix,feat,chore,docs,style,refactor,perf,test"
          prefix_case_sensitive: true
          github_token: ${{ github.token }}
