name: "Release"

on: workflow_dispatch

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
          release-count: 0

      - name: Create Release
        run: |
          gh release create ${{ env.version }} -n "${{ env.message }}" -t "${{ env.name }}"
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
          version: ${{ steps.changelog.outputs.tag }}
          message: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
